  customer_ui:
    build: ./customer-ui
    ports:
      - "5173:5173"
    environment:
      TZ: ${TZ}
    volumes:
      - ${CUSTOMER_UI_NODE_CACHE}:/root/.npm
      - ${CUSTOMER_UI_LOGS}:/app/logs
    depends_on:
      - api
