  admin_ui:
    build: ./admin-ui
    env_file:
      - ../.env
    environment:
      VITE_API_BASE: ${VITE_API_BASE:-}
      VITE_API_PROTOCOL: ${VITE_API_PROTOCOL:-https}
      VITE_API_SUBDOMAIN: ${VITE_API_SUBDOMAIN:-api}
      VITE_BASE_DOMAIN: ${BASE_DOMAIN:-test.myitnetwork.de}
    ports:
      - "5173:5173"
    depends_on:
      - api
